// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAxao3ISvXLTVdkdsBOiF73LwY_nazQUI',
    appId: '1:553246020161:web:cbae2155334ff0cc886cc0',
    messagingSenderId: '553246020161',
    projectId: 'flutter-final-e479d',
    authDomain: 'flutter-final-e479d.firebaseapp.com',
    databaseURL: 'https://flutter-final-e479d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-final-e479d.appspot.com',
    measurementId: 'G-YYT476318N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTAvBGxoUIwMD8emVgbkxisqXOqRAXgdw',
    appId: '1:553246020161:android:38da351a62255292886cc0',
    messagingSenderId: '553246020161',
    projectId: 'flutter-final-e479d',
    databaseURL: 'https://flutter-final-e479d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-final-e479d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm7dGp3sFGVBSK8-vgeurK3CvNcJfr39Y',
    appId: '1:553246020161:ios:972d4c246bf282a4886cc0',
    messagingSenderId: '553246020161',
    projectId: 'flutter-final-e479d',
    databaseURL: 'https://flutter-final-e479d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-final-e479d.appspot.com',
    iosBundleId: 'com.example.projectFinalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm7dGp3sFGVBSK8-vgeurK3CvNcJfr39Y',
    appId: '1:553246020161:ios:bdf65dc1d7a8fedd886cc0',
    messagingSenderId: '553246020161',
    projectId: 'flutter-final-e479d',
    databaseURL: 'https://flutter-final-e479d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-final-e479d.appspot.com',
    iosBundleId: 'com.example.projectFinalMobile.RunnerTests',
  );
}
